from pathlib import Path

INDEX = Path("site/index.html")
html = INDEX.read_text(encoding="utf-8")

new_figures = """<figure><a class='gallery-link' href='#wordcloud-stolz'><img src='assets/teamtage/2026-07-10/wordcloud-stolz.svg' alt='Wordcloud zur Frage: Worauf bist du in unserer Kita besonders stolz?' ></a><figcaption>Worauf bist du in unserer Kita besonders stolz?</figcaption></figure><figure><a class='gallery-link' href='#wordcloud-teamarbeit'><img src='assets/teamtage/2026-07-10/wordcloud-teamarbeit.svg' alt='Wordcloud zur Frage: Welcher Begriff beschreibt für dich gute Teamarbeit?' ></a><figcaption>Welcher Begriff beschreibt für dich gute Teamarbeit?</figcaption></figure><figure><a class='gallery-link' href='#wordcloud-handbuch'><img src='assets/teamtage/2026-07-10/wordcloud-handbuch.svg' alt='Wordcloud zur Frage: Was darf in unserem Handbuch auf keinen Fall fehlen?' ></a><figcaption>Was darf in unserem Handbuch auf keinen Fall fehlen?</figcaption></figure>"""

import re

if "wordcloud-stolz" not in html:
    figure_pattern = re.compile(
        r"(<figure><a class=[\"']gallery-link[\"'] href=[\"']#wordcloud-kita-jahr-rueckblick[\"']>.*?<figcaption>Welches Wort beschreibt unser vergangenes Kita-Jahr am besten\?</figcaption></figure>)"
    )
    html, count = figure_pattern.subn(r"\1" + new_figures, html, count=1)
    if count != 1:
        raise SystemExit("Anker für die Wordcloud-Galerie wurde nicht gefunden.")

note_pattern = re.compile(
    r"<div class=[\"']note[\"']>\s*Besonders häufig genannt wurden Kommunikation, Motivation, Absprachen und Struktur\..*?Aus diesen Ergebnissen entwickeln wir unser gemeinsames Motto weiter\.\s*</div>"
)
new_note = "<div class='note'> Die Ergebnisse zeigen, was unser Team bewegt: Zusammenhalt, Humor, Hilfsbereitschaft, Wertschätzung und Vertrauen prägen die Zusammenarbeit. Besonders stolz sind wir auf unser Team und den Zusammenhalt. Für das Handbuch wurde die Morgenbesprechung als zentraler Inhalt genannt. </div>"
html = note_pattern.sub(new_note, html, count=1)

new_lightboxes = """<div id='wordcloud-stolz' class='lightbox'><a class='lightbox-close-area' href='#macht-uns-aus' aria-label='Vollbild schließen'></a><div class='lightbox-content'><a class='lightbox-close' href='#macht-uns-aus' aria-label='Vollbild schließen'>×</a><img src='assets/teamtage/2026-07-10/wordcloud-stolz.svg' alt='Wordcloud zur Frage: Worauf bist du in unserer Kita besonders stolz?'><p>Worauf bist du in unserer Kita besonders stolz?</p></div></div><div id='wordcloud-teamarbeit' class='lightbox'><a class='lightbox-close-area' href='#macht-uns-aus' aria-label='Vollbild schließen'></a><div class='lightbox-content'><a class='lightbox-close' href='#macht-uns-aus' aria-label='Vollbild schließen'>×</a><img src='assets/teamtage/2026-07-10/wordcloud-teamarbeit.svg' alt='Wordcloud zur Frage: Welcher Begriff beschreibt für dich gute Teamarbeit?'><p>Welcher Begriff beschreibt für dich gute Teamarbeit?</p></div></div><div id='wordcloud-handbuch' class='lightbox'><a class='lightbox-close-area' href='#macht-uns-aus' aria-label='Vollbild schließen'></a><div class='lightbox-content'><a class='lightbox-close' href='#macht-uns-aus' aria-label='Vollbild schließen'>×</a><img src='assets/teamtage/2026-07-10/wordcloud-handbuch.svg' alt='Wordcloud zur Frage: Was darf in unserem Handbuch auf keinen Fall fehlen?'><p>Was darf in unserem Handbuch auf keinen Fall fehlen?</p></div></div>"""

if "id='wordcloud-stolz'" not in html and 'id="wordcloud-stolz"' not in html:
    lightbox_pattern = re.compile(r"(<div id=[\"']wordcloud-kita-wichtig[\"'] class=[\"']lightbox[\"']>)")
    html, count = lightbox_pattern.subn(new_lightboxes + r"\1", html, count=1)
    if count != 1:
        raise SystemExit("Anker für die Vollbildansichten wurde nicht gefunden.")

INDEX.write_text(html, encoding="utf-8")

assets = Path("site/assets/teamtage/2026-07-10")
assets.mkdir(parents=True, exist_ok=True)

assets.joinpath("wordcloud-stolz.svg").write_text("""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1031 565" role="img" aria-labelledby="title desc"><title id="title">Worauf bist du in unserer Kita besonders stolz?</title><desc id="desc">Wordcloud mit den größten Begriffen Team und Zusammenhalt.</desc><rect width="1031" height="565" fill="#fff"/><g font-family="Arial,Helvetica,sans-serif"><text x="36" y="88" font-size="35" fill="#111">Worauf bist du in unserer Kita besonders stolz?</text><text x="465" y="338" font-size="59" fill="#5368e8">team</text><text x="326" y="384" font-size="57" fill="#c84b45">zusammenhalt</text><text x="327" y="242" font-size="21" fill="#5368e8">meine kollegen</text><text x="516" y="246" font-size="20" fill="#8c3c3a">kollegen</text><text x="626" y="257" font-size="20" fill="#6f62d9">hilfsbereitschaft</text><text x="199" y="300" font-size="20" fill="#6f62d9">auf unser team</text><text x="381" y="291" font-size="20" fill="#c84b45">feste</text><text x="450" y="270" font-size="20" fill="#8c3c3a">entwicklung</text><text x="586" y="296" font-size="20" fill="#2f3f88">außenwirkung</text><text x="353" y="328" font-size="20" fill="#6f62d9">das team</text><text x="729" y="336" font-size="20" fill="#2f3f88">geduld</text><text x="747" y="362" font-size="19" fill="#c84b45">vielseitig</text><text x="307" y="414" font-size="19" fill="#5368e8">entwicklungen von kindern</text><text x="601" y="419" font-size="19" fill="#2f3f88">absprachen oben</text></g></svg>""", encoding="utf-8")

assets.joinpath("wordcloud-teamarbeit.svg").write_text("""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1038 580" role="img" aria-labelledby="title desc"><title id="title">Welcher Begriff beschreibt für dich gute Teamarbeit?</title><desc id="desc">Wordcloud mit Humor, Hilfsbereitschaft, Wertschätzung und Vertrauen.</desc><rect width="1038" height="580" fill="#fff"/><g font-family="Arial,Helvetica,sans-serif"><text x="36" y="96" font-size="35" fill="#111">Welcher Begriff beschreibt für dich gute Teamarbeit?</text><text x="433" y="327" font-size="67" fill="#5368e8">humor</text><text x="385" y="369" font-size="42" fill="#c84b45">hilfsbereitschaft</text><text x="490" y="414" font-size="42" fill="#6f62d9">wertschätzung</text><text x="514" y="277" font-size="42" fill="#2f3f88">vertrauen</text><text x="352" y="238" font-size="16" fill="#5368e8">kommunizieren</text><text x="270" y="266" font-size="17" fill="#2f3f88">auf augenhöhe</text><text x="413" y="258" font-size="17" fill="#2f3f88">absprachen</text><text x="513" y="238" font-size="16" fill="#8c3c3a">miteinander kommunizieren</text><text x="723" y="275" font-size="16" fill="#6f62d9">unterstützung</text><text x="337" y="289" font-size="16" fill="#6f62d9">miteinander</text><text x="336" y="307" font-size="16" fill="#5368e8">gemeinsam</text><text x="684" y="301" font-size="16" fill="#c84b45">gute laune</text><text x="191" y="336" font-size="16" fill="#2f3f88">stärken und schwächen</text><text x="279" y="363" font-size="16" fill="#6f62d9">empathie</text><text x="684" y="322" font-size="16" fill="#8c3c3a">gegenseitiges unterstütze</text><text x="397" y="393" font-size="16" fill="#5368e8">respekt</text><text x="709" y="355" font-size="16" fill="#c84b45">selbst mitdenken</text><text x="707" y="378" font-size="16" fill="#8c3c3a">vertrauen</text><text x="404" y="438" font-size="16" fill="#c84b45">absprachen und einhalten</text></g></svg>""", encoding="utf-8")

assets.joinpath("wordcloud-handbuch.svg").write_text("""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1033 577" role="img" aria-labelledby="title desc"><title id="title">Was darf in unserem Handbuch auf keinen Fall fehlen?</title><desc id="desc">Wordcloud mit dem großen Begriff Morgenbesprechung und weiteren gewünschten Inhalten.</desc><rect width="1033" height="577" fill="#fff"/><g font-family="Arial,Helvetica,sans-serif"><text x="36" y="96" font-size="35" fill="#111">Was darf in unserem Handbuch auf keinen Fall fehlen?</text><text x="176" y="337" font-size="61" fill="#5368e8">morgenbesprechung</text><text x="410" y="231" font-size="19" fill="#8c3c3a">gemeinsame gute erlebnisse</text><text x="240" y="265" font-size="19" fill="#c84b45">werkstattregeln</text><text x="398" y="270" font-size="19" fill="#5368e8">dienstplan</text><text x="517" y="259" font-size="19" fill="#2f3f88">frühdienst</text><text x="655" y="262" font-size="19" fill="#8c3c3a">motivation</text><text x="511" y="288" font-size="18" fill="#8c3c3a">details spätdienst</text><text x="756" y="284" font-size="18" fill="#8c3c3a">zeitplanung</text><text x="378" y="294" font-size="18" fill="#2f3f88">lob</text><text x="397" y="363" font-size="18" fill="#c84b45">aktualität</text><text x="675" y="362" font-size="18" fill="#c84b45">infos</text><text x="265" y="383" font-size="18" fill="#6f62d9">geburtstage</text><text x="413" y="386" font-size="18" fill="#2f3f88">arbeitszeiten</text><text x="548" y="374" font-size="18" fill="#6f62d9">db protokolle</text><text x="290" y="410" font-size="18" fill="#6f62d9">lustige fotos</text><text x="432" y="414" font-size="18" fill="#c84b45">diskriminierung</text><text x="604" y="405" font-size="18" fill="#5368e8">informiert</text><text x="715" y="399" font-size="18" fill="#6f62d9">abläufe</text><text x="284" y="439" font-size="18" fill="#5368e8">termine db feste planung</text><text x="555" y="444" font-size="18" fill="#2f3f88">wichtige infos</text></g></svg>""", encoding="utf-8")
